### ISSUE TITLE
CPU NOT RESPONDING

### ISSUE THREAD

**Issue by ByerRA** [RattyDAVE/cray1#1]
I tried this docker image and when I follow the directions to bring up the CRAY1 when I issue the "START @dk0:COS_117 @dk0:INSTALL" command I get the following...

MFINIT: COMPLETE
CPU <-> MIOP CHANNEL INIT
CPU NOT RESPONDING - RETRY?

No matter what I do, I can't get past this point.

When I check the logs for the running image I see the following error...

mkdir: can't create directory 'dump': File exists

**Comment by RattyDAVE** [comment]
Let me check and Ill get back to you...

**Comment by RattyDAVE** [comment]
I can duplicate the issue.

![image](https://user-images.githubusercontent.com/9049822/153034939-a1860dde-25b0-45dc-8169-bb1e769032c2.png)

Give me a bit and ill look into this.

**Comment by ByerRA** [comment]
Thanks.

**Comment by RattyDAVE** [comment]
Fixed!

Please try now.

Issue was to do with the CLOCK.

**Comment by ByerRA** [comment]
Thanks, that did it, it's now working like it should :)

**Comment by RattyDAVE** [comment]
Have confirmation of working
